plugins {
    id 'com.android.library'
}

android {
    namespace 'com.termux.x11'
    compileSdk = 36
    ndkVersion = "29.0.14206865"

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 36
        buildConfigField 'String', 'VERSION_NAME', '"1.03.01-embedded"'
        buildConfigField 'String', 'APPLICATION_ID', '"com.qali.dterm"'
        consumerProguardFiles 'proguard-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging false
        }
    }

    buildFeatures {
        buildConfig true
    }

    lint {
        disable 'AppCompatCustomView'
    }
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.21'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7'
    implementation 'androidx.preference:preference:1.2.1'
}
